### ISSUE TITLE
No instance_mask for the RedWood dataset?

### ISSUE THREAD

**Issue by Bingo-1996** [roym899/pose_and_shape_evaluation#19]
Hi. Thank you for releasing such a wonderful work~
I'm trying to evaluate pretrained models such as CR-Net on the redwood dataset, and I have configured the dataset as required. However, when I  run  the evaluate code there is an error regarding the absence of instance masks? Do I need any additional processing for the RedWood dataset? 
I'm looking forward to your reply!? looking forward to your reply. 

<img width="462" alt="微信图片_20230609202158" src="https://github.com/roym899/pose_and_shape_evaluation/assets/69563953/342dce74-53b0-40fb-8f03-bf8439b9256a">

**Comment by roym899** [comment]
I'll look into it tomorrow and see if I can reproduce the issue.

**Comment by Bingo-1996** [comment]
Thank you very much for your quick reply. After resetting the relevant code, I have successfully tested the RedWood dataset and also successfully tested my own model. Sorry to bother you, thank you again!

**Comment by roym899** [comment]
Great, happy to hear.
